### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/zero-boilerplate-redux#2]
- [x] 404 page
- [x] Delete gist
- [ ] Create gist
  - [x] Create with description
  - [ ] Create with `n` files
- [ ] Update gist
  - [x] Update description
  - [x] Update existing file
  - [ ] Delete file
  - [ ] Add new file
- [ ] Add support for app loading without credentials
- [x] Add better README
